/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from 'motia'

declare module 'motia' {
  interface Streams {}

  interface Enqueues {
    'copy.created': unknown
    'copy.status_changed': unknown
    'wish.created': unknown
    'edition.enriched': unknown
    'stale_listings.report': unknown
  }
}
